#CuboidCheck Server-to-Server Configuration
[general]
	#What role does this server play?
	#SERVER_A: Requests block data from Server B
	#SERVER_B: Listens and sends block data to Server A
	#STANDALONE: Does nothing (normal server)
	#Allowed Values: SERVER_A, SERVER_B, STANDALONE
	serverMode = "SERVER_B"
	#The TCP port used for communication.
	# Default: 8083
	# Range: 1024 ~ 65536
	serverBPort = 8082
	#The IP address of Server B (Only used if this is Server A).
	serverBIp = "127.0.0.1"
